
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import proyecto.Ventana;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vic
 */
public class Home extends javax.swing.JFrame {
    Timer t;
    int x = 0;
    ActionListener Al;

    String[] random = new String[]{"Corriendo la aplicación",
        "Cargando Modulos",
        "Configurando Metodos",
        "Estableciendo Parametros",
        "Habilitando Archivos"};
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        ColorUIResource colorResource = new ColorUIResource(Color.green.darker().darker());
        UIManager.put("nimbusOrange",colorResource);
        
        Al = (ActionEvent ae) -> {

            int Min = 1;
            int Max = 10;
            int s = Min + (int) (Math.random() * ((Max - Min) + 1));
            x = x + s;
            Barra.setValue(x);
            int ran = 0 + (int) (Math.random() * ((3 - 0) + 1));
            Etiqueta.setText(random[ran]);
            
            if (Barra.getValue() == 100) {
                this.dispose();
                t.stop();
              /*Aquí va el siguiente form*/
                Ventana menu = new Ventana();
                menu.setVisible(true);
                //JOptionPane.showMessageDialog(null,"Aquí el siguiente form!");
            }
        };
        t = new Timer(300, Al);

        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiqueta = new javax.swing.JLabel();
        Barra = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(498, 270));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        Etiqueta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Etiqueta.setForeground(new java.awt.Color(255, 255, 255));
        Etiqueta.setText("------------------------");
        getContentPane().add(Etiqueta);
        Etiqueta.setBounds(20, 230, 230, 20);

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.setForeground(new java.awt.Color(255, 255, 255));
        Barra.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        Barra.setBorderPainted(false);
        getContentPane().add(Barra);
        Barra.setBounds(20, 250, 460, 10);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("3JVC");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 140, 60);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("& ENCRYPTING");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 140, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logoas.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 10, 224, 210);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("COMPRESSING");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo-a.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(498, 168));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
