import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import proyecto.Ventana;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vic
 */
public class Inicio extends javax.swing.JFrame {
    Timer t;
    int x = 0;
    ActionListener Al;

    String[] random = new String[]{"Corriendo la aplicación",
        "Un poco más para iniciar",
        "¡Ya casi estamos ahí!",
        "¡Espéranos un poco más!"};
    /**
     * Creates new form Inicio
     */
    public Inicio() {
   
        initComponents();
        
        ImageIcon jvc = new ImageIcon(getClass().getResource("/imagenes/Logo.png"));
        ImageIcon icono = new ImageIcon(jvc.getImage().getScaledInstance(Background.getWidth(),Background.getHeight(),Image.SCALE_DEFAULT));
        ColorUIResource colorResource = new ColorUIResource(Color.green.darker().darker());
        UIManager.put("nimbusOrange",colorResource);
        Background.setIcon(icono);
        
         Al = (ActionEvent ae) -> {
            int Min = 1;
            int Max = 25;
            int s = Min + (int) (Math.random() * ((Max - Min) + 1));
            x = x + s;
            Barra.setValue(x);
            int ran = 0 + (int) (Math.random() * ((3 - 0) + 1));
            Etiqueta.setText("Cargando... " + random[ran]);

            if (Barra.getValue() == 100) {
                this.dispose();
                t.stop();
              /*Aquí va el siguiente form*/
                Ventana menu = new Ventana();
                menu.setVisible(true);
                JOptionPane.showMessageDialog(null,"Aquí el siguiente form!");
            }
        };
        t = new Timer(1050, Al);

        t.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra = new javax.swing.JProgressBar();
        Etiqueta = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        setAlwaysOnTop(true);
        setMaximumSize(null);
        setMinimumSize(null);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(519, 264));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Barra);
        Barra.setBounds(10, 230, 500, 10);

        Etiqueta.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Etiqueta);
        Etiqueta.setBounds(150, 240, 250, 20);

        Titulo.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("3JVC Compressor");
        getContentPane().add(Titulo);
        Titulo.setBounds(190, 10, 170, 22);
        getContentPane().add(Background);
        Background.setBounds(-10, 0, 530, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JProgressBar Barra;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
